# Panda博客系统一键搭建脚本
version: '3'
services:
 web:
   build: .
   depends_on:
    - db
   restart: always
   ports:
    - "9845:80"
   environment:
    - MYSQL_DB=Data Source=db;Port=53200;User ID=qingcheng;Password=qingcheng; Initial Catalog=qingcheng;Charset=utf8; SslMode=none;Min pool size=1
   links:
    - db
 db:
   image: "mysql/mysql-server"
   restart: always
   ports:
    - "53200:3306"
   environment:
      MYSQL_ROOT_PASSWORD: qingcheng
      MYSQL_DATABASE: qingcheng
      MYSQL_USER: qingcheng
      MYSQL_PASSWORD: qingcheng
      LANG: C.UTF-8
  #  volumes:
    # - /data/mysql/data/:/var/lib/mysql/  #映射mysql的数据目录到宿主机，保存数据
    # - /data/mysql/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
   command: --default-authentication-plugin=mysql_native_password #这行代码解决无法访问的问题