version: "3"
  services:
    web:
      image: registry.cn-hangzhou.aliyuncs.com/chenxindev/panda:2111092255
      ports:
        - 9845:80
      environment:
        MYSQL_DB: Data Source=129.211.57.2;Port=53200;User ID=qingcheng;Password=qingcheng; Initial Catalog=q_blog;Charset=utf8; SslMode=none;Min pool size=1
