version: '3'
services:
  web:
    image: iwscl/panda-blog:latest
    ports:
      - 9845:5005
    volumes:
      - "/var/panda-blog-content:/app/Content"
    environment:
      - MYSQL=mysql连接
    restart: always
