/**
 * 后台api文档
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Accounts { 
    id?: string;
    addTime?: Date;
    updateTime?: Date;
    userName?: string;
    nickName?: string;
    email?: string;
    passwd?: string;
    lastLoginTime?: Date;
    lockedTime?: Date;
    loginFailCount?: number;
    isDisable?: boolean;
}