/**
 * 后台api文档
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AccountStatus = 0 | 1 | 2;

export const AccountStatus = {
    NUMBER_0: 0 as AccountStatus,
    NUMBER_1: 1 as AccountStatus,
    NUMBER_2: 2 as AccountStatus
};