/**
 * ��̨api�ĵ�
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RecentAccessHistory { 
    /**
     * 访客唯一ID
     */
    uId?: string;
    /**
     * 访问地址
     */
    url?: string;
    /**
     * 访问IP
     */
    ip?: string;
    ua?: string;
    /**
     * 操作系统
     */
    os?: string;
    /**
     * 浏览器
     */
    browser?: string;
    /**
     * referer
     */
    referer?: string;
    /**
     * 添加时间
     */
    addTime?: Date;
    /**
     * Ip所属区域
     */
    region?: string;
}