/**
 * ��̨api�ĵ�
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UploadBase64Model { 
    base64: string;
    /**
     * 0不重写宽高
     */
    w?: number;
    h?: number;
}