/**
 * Panda.Site
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AuditStatusEnum = 0 | 1 | 2;

export const AuditStatusEnum = {
    NUMBER_0: 0 as AuditStatusEnum,
    NUMBER_1: 1 as AuditStatusEnum,
    NUMBER_2: 2 as AuditStatusEnum
};