/**
 * Panda.Site
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RecentAccessHistory { 
    uId?: string;
    url?: string;
    ip?: string;
    ua?: string;
    os?: string;
    browser?: string;
    referer?: string;
    addTime?: Date;
    region?: string;
}