/**
 * 后台api文档
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AccountLoginRequest } from '../model/accountLoginRequest';
import { AccountRespPageDto } from '../model/accountRespPageDto';
import { ChangePwdRequest } from '../model/changePwdRequest';
import { CreateAdminAccountRequest } from '../model/createAdminAccountRequest';
import { LoginStatusResult } from '../model/loginStatusResult';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AccountService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public adminAccountChangePwdPost(body?: ChangePwdRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public adminAccountChangePwdPost(body?: ChangePwdRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public adminAccountChangePwdPost(body?: ChangePwdRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public adminAccountChangePwdPost(body?: ChangePwdRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/admin/Account/ChangePwd`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 获取用户列表
     * 
     * @param index 
     * @param size 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public adminAccountGetAccountListGet(index: number, size: number, observe?: 'body', reportProgress?: boolean): Observable<AccountRespPageDto>;
    public adminAccountGetAccountListGet(index: number, size: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AccountRespPageDto>>;
    public adminAccountGetAccountListGet(index: number, size: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AccountRespPageDto>>;
    public adminAccountGetAccountListGet(index: number, size: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (index === null || index === undefined) {
            throw new Error('Required parameter index was null or undefined when calling adminAccountGetAccountListGet.');
        }

        if (size === null || size === undefined) {
            throw new Error('Required parameter size was null or undefined when calling adminAccountGetAccountListGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (index !== undefined && index !== null) {
            queryParameters = queryParameters.set('Index', <any>index);
        }
        if (size !== undefined && size !== null) {
            queryParameters = queryParameters.set('Size', <any>size);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<AccountRespPageDto>('get',`${this.basePath}/admin/Account/GetAccountList`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 检查当前状态
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public adminAccountIsLoginGet(observe?: 'body', reportProgress?: boolean): Observable<LoginStatusResult>;
    public adminAccountIsLoginGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LoginStatusResult>>;
    public adminAccountIsLoginGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LoginStatusResult>>;
    public adminAccountIsLoginGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<LoginStatusResult>('get',`${this.basePath}/admin/Account/IsLogin`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public adminAccountLoginOutGet(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public adminAccountLoginOutGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public adminAccountLoginOutGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public adminAccountLoginOutGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/admin/Account/LoginOut`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 登录
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public adminAccountLoginPost(body?: AccountLoginRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public adminAccountLoginPost(body?: AccountLoginRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public adminAccountLoginPost(body?: AccountLoginRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public adminAccountLoginPost(body?: AccountLoginRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/admin/Account/Login`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public adminCreateAdminAccountPost(body?: CreateAdminAccountRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public adminCreateAdminAccountPost(body?: CreateAdminAccountRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public adminCreateAdminAccountPost(body?: CreateAdminAccountRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public adminCreateAdminAccountPost(body?: CreateAdminAccountRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/admin/createAdminAccount`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
