export * from './account.service';
import { AccountService } from './account.service';
export * from './category.service';
import { CategoryService } from './category.service';
export * from './common.service';
import { CommonService } from './common.service';
export * from './friendLink.service';
import { FriendLinkService } from './friendLink.service';
export * from './home.service';
import { HomeService } from './home.service';
export * from './post.service';
import { PostService } from './post.service';
export * from './rss.service';
import { RssService } from './rss.service';
export * from './siteStatistic.service';
import { SiteStatisticService } from './siteStatistic.service';
export * from './statistic.service';
import { StatisticService } from './statistic.service';
export * from './tag.service';
import { TagService } from './tag.service';
export * from './test.service';
import { TestService } from './test.service';
export const APIS = [AccountService, CategoryService, CommonService, FriendLinkService, HomeService, PostService, RssService, SiteStatisticService, StatisticService, TagService, TestService];
