/**
 * 后台api文档
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CategoryAddOrUpdate } from '../model/categoryAddOrUpdate';
import { CategoryItem } from '../model/categoryItem';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CategoryService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public adminCategoryAddOrUpdatePost(body?: CategoryAddOrUpdate, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public adminCategoryAddOrUpdatePost(body?: CategoryAddOrUpdate, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public adminCategoryAddOrUpdatePost(body?: CategoryAddOrUpdate, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public adminCategoryAddOrUpdatePost(body?: CategoryAddOrUpdate, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/admin/Category/AddOrUpdate`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param categoryId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public adminCategoryDeleteDelete(categoryId?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public adminCategoryDeleteDelete(categoryId?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public adminCategoryDeleteDelete(categoryId?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public adminCategoryDeleteDelete(categoryId?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (categoryId !== undefined && categoryId !== null) {
            queryParameters = queryParameters.set('CategoryId', <any>categoryId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/admin/Category/Delete`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public adminCategoryGetGet(id?: number, observe?: 'body', reportProgress?: boolean): Observable<CategoryItem>;
    public adminCategoryGetGet(id?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CategoryItem>>;
    public adminCategoryGetGet(id?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CategoryItem>>;
    public adminCategoryGetGet(id?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (id !== undefined && id !== null) {
            queryParameters = queryParameters.set('id', <any>id);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<CategoryItem>('get',`${this.basePath}/admin/Category/Get`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param index 
     * @param size 
     * @param cateName 
     * @param isShow 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public adminCategoryGetListGet(index: number, size: number, cateName?: string, isShow?: boolean, observe?: 'body', reportProgress?: boolean): Observable<Array<CategoryItem>>;
    public adminCategoryGetListGet(index: number, size: number, cateName?: string, isShow?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CategoryItem>>>;
    public adminCategoryGetListGet(index: number, size: number, cateName?: string, isShow?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CategoryItem>>>;
    public adminCategoryGetListGet(index: number, size: number, cateName?: string, isShow?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (index === null || index === undefined) {
            throw new Error('Required parameter index was null or undefined when calling adminCategoryGetListGet.');
        }

        if (size === null || size === undefined) {
            throw new Error('Required parameter size was null or undefined when calling adminCategoryGetListGet.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (cateName !== undefined && cateName !== null) {
            queryParameters = queryParameters.set('CateName', <any>cateName);
        }
        if (isShow !== undefined && isShow !== null) {
            queryParameters = queryParameters.set('IsShow', <any>isShow);
        }
        if (index !== undefined && index !== null) {
            queryParameters = queryParameters.set('Index', <any>index);
        }
        if (size !== undefined && size !== null) {
            queryParameters = queryParameters.set('Size', <any>size);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<CategoryItem>>('get',`${this.basePath}/admin/Category/GetList`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
