# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3

    
    - uses: actions/setup-node@v2
      with:
        node-version: '18.14.2'
    - name: 打包Vue文件
      working-directory: Admin.Client
      run: npm install -g yarn && yarn && yarn build
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: 打包asp.net文件
      working-directory: Server/PandaSite
      run: dotnet restore
    - name: Build
      run: echo $(pwd) && dotnet publish -o ./publish
    - name: 打印目录
      run: tree ./publish
    
    
