name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: 登录docker
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PWD }}
        registry: ${{ secrets.DOCKER_REGISTRY }}
        
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        name=panda-blog:$(date +%s)
        docker build . --file dockerfile --tag $name
        docker tag $name  iwscl/$name
        docker push iwscl/$name

