name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: 登录docker
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PWD }}
        registry: ${{ secrets.DOCKER_REGISTRY }}
        
    
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
  
    - name: Set up Docker Buildx
      run: |
        name=iwscl/panda-blog:$(date +%s)
        docker buildx build . --file dockerfile --platform linux/amd64,linux/arm64 -t $name -t iwscl/panda-blog:latest --push

